Remove deprecated tweet tag
Hugo build failed due to:

Run hugo --minify
Start building sites …
hugo v0.160.1-d6bc8165e62b29d7d70ede01ed01d0f88de327e6 linux/amd64 BuildDate=2026-04-08T14:02:42Z VendorInfo=gohugoio

ERROR The "twitter", "tweet", and "twitter_simple" shortcodes were deprecated in v0.142.0 and removed in v0.156.0. Please use the "x" shortcode instead.
ERROR error building site: logged 1 error(s)
Total in 101 ms
Error: Process completed with exit code 1.

This updates tag to accepted X format